# Generated by Django 4.2 on 2023-04-19 15:28

import code10.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0003_alter_userstatus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChats',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code10.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupChatSender', to='code10.user')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userfriendrequest',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='code10.user'),
        ),
        migrations.AlterField(
            model_name='userfriendrequest',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='code10.user'),
        ),
        migrations.CreateModel(
            name='UserChats',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='unread', max_length=100)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='code10.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='code10.user')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserChatFiles',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to=code10.models.userChatFile_directory_path)),
                ('fileType', models.CharField(blank=True, max_length=100)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='code10.userchats')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupChatStatus',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='unread', max_length=100)),
                ('groupChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code10.groupchats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupChatUser', to='code10.user')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupChatFiles',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to=code10.models.groupChatFile_directory_path)),
                ('fileType', models.CharField(blank=True, max_length=100)),
                ('groupChat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='code10.groupchats')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
