# Generated by Django 4.2 on 2023-04-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0004_groupchats_alter_userfriendrequest_user1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupChats',
            new_name='GroupChat',
        ),
        migrations.RenameModel(
            old_name='GroupChatFiles',
            new_name='GroupChatFile',
        ),
        migrations.RenameModel(
            old_name='UserChats',
            new_name='UserChat',
        ),
        migrations.RenameModel(
            old_name='UserChatFiles',
            new_name='UserChatFile',
        ),
    ]
