# Generated by Django 4.2 on 2023-05-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0008_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendrequest',
            name='by',
            field=models.CharField(default='user1', max_length=100),
        ),
    ]
