# Generated by Django 4.2 on 2023-05-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0009_userfriendrequest_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriendrequest',
            name='by',
        ),
    ]
