# Generated by Django 4.2 on 2023-05-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0010_remove_userfriendrequest_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriend',
            name='by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
