# Generated by Django 4.2 on 2023-05-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0011_userfriend_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriend',
            name='by',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
