# Generated by Django 4.2 on 2023-05-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0012_alter_userfriend_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='code10.userfriend'),
            preserve_default=False,
        ),
    ]
