# Generated by Django 4.2.1 on 2023-05-21 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0013_userchat_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='groupHash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
