# Generated by Django 4.2.1 on 2023-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0015_alter_group_options_group_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
