# Generated by Django 4.2.1 on 2023-05-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code10', '0017_groupinviteslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinviteslug',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='code10.group'),
        ),
        migrations.AlterField(
            model_name='groupinviteslug',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
